import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { BadgeCheck, BedDouble, Bath, Maximize2, MapPin, Sparkles, ShieldCheck, ArrowLeft } from 'lucide-react';
import { getProperty, properties, money } from '@/lib/atheeldar-data';
import { Breadcrumbs } from '@/components/atheeldar/SiteShell';
import { PropertyActionPanel } from '@/components/atheeldar/InteractiveTools';
import { PropertyCard } from '@/components/atheeldar/PropertyCard';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=getProperty(slug);return p?{title:p.title,description:p.description}:{title:'عقار غير موجود'}}
export function generateStaticParams(){return properties.map(p=>({slug:p.slug}))}
export default async function PropertyDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=getProperty(slug);if(!p)notFound();const related=properties.filter(x=>x.city===p.city&&x.slug!==p.slug).slice(0,3);return <>
  <section className="detailTop shell"><Breadcrumbs items={[{label:'الرئيسية',href:'/'},{label:'العقارات',href:'/properties'},{label:p.title}]}/><div className="detailTitleRow"><div><div className="detailBadges"><span>{p.badge}</span>{p.verified&&<span className="verified"><BadgeCheck size={15}/> إعلان موثق تجريبيًا</span>}</div><h1>{p.title}</h1><p><MapPin size={16}/>{p.city} · {p.district}</p></div><div className="detailScore"><span>تقييم أثيلدار</span><b>{p.score}</b><small>/100</small></div></div></section>
  <section className="galleryGrid shell"><img className="galleryMain" src={p.gallery[0]} alt={p.title}/>{p.gallery.slice(1,3).map((g,i)=><img key={g} src={g} alt={`${p.title} ${i+2}`}/>)}<div className="galleryCount">معرض الصور · {p.gallery.length} صور نموذجية</div></section>
  <section className="section shell detailLayout"><div className="detailBody"><div className="detailSpecs"><span><BedDouble/>{p.beds||'—'}<small>غرف</small></span><span><Bath/>{p.baths||'—'}<small>حمامات</small></span><span><Maximize2/>{money(p.area)}<small>م²</small></span><span><ShieldCheck/>موثق<small>تجريبيًا</small></span></div><h2>عن العقار</h2><p className="leadText">{p.description}</p><h3>المزايا والتجهيزات</h3><div className="featurePills">{p.features.map(f=><span key={f}>{f}</span>)}</div><div className="insightCard"><Sparkles/><div><b>قراءة أثيلدار الذكية</b><p>العقار يقع ضمن شريحة {p.score>=92?'ممتازة':'قوية'} في نموذج التقييم، مع سعر تقريبي {money(Math.round(p.price/p.area))} ر.س للمتر. هذه القراءة توضيحية وليست تقييمًا رسميًا.</p></div></div><div className="locationBlock"><div><p className="eyebrow">الموقع</p><h2>{p.district} · {p.city}</h2><p>صفحة الحي تعطيك سياقًا أوسع عن الطلب والأسعار وطبيعة المنطقة قبل اتخاذ قرار المعاينة.</p><Link href={`/neighborhoods/${p.neighborhoodSlug}`} className="textLink">فتح ملف الحي <ArrowLeft/></Link></div><div className="miniMap"><span style={{left:`${p.coordinates.x}%`,top:`${p.coordinates.y}%`}} className="focusPin">{p.title}</span></div></div></div><PropertyActionPanel property={p}/></section>
  {related.length>0&&<section className="section softSection"><div className="shell"><div className="sectionHead"><div><p className="eyebrow">قد يناسبك أيضًا</p><h2>عقارات في {p.city}</h2></div><Link href="/properties" className="textLink">كل العقارات <ArrowLeft/></Link></div><div className="propertyGrid">{related.map(x=><PropertyCard key={x.slug} p={x}/>)}</div></div></section>}
</>}
