import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, BarChart3, Footprints, Home, TrendingUp } from 'lucide-react';
import { neighborhoods, getNeighborhood, properties } from '@/lib/atheeldar-data';
import { Breadcrumbs } from '@/components/atheeldar/SiteShell';
import { PropertyCard } from '@/components/atheeldar/PropertyCard';
import { NeighborhoodExperience } from '@/components/atheeldar/ContextExperiences';
import { NeighborhoodDailyRadius } from '@/components/atheeldar/Phase10Suite';
export function generateStaticParams(){return neighborhoods.map(n=>({slug:n.slug}))}
export default async function NeighborhoodPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const n=getNeighborhood(slug);if(!n)notFound();const ps=properties.filter(p=>p.neighborhoodSlug===slug||p.city===n.city).slice(0,3);return <><section className="neighborhoodHero"><img src={n.image}/><div className="projectDetailShade"/><div className="shell neighborhoodHeroContent"><Breadcrumbs items={[{label:'الرئيسية',href:'/'},{label:'الأحياء',href:'/neighborhoods'},{label:n.name}]}/><p className="eyebrow light">{n.city} · {n.label}</p><h1>{n.name}</h1><p>{n.summary}</p></div></section><section className="section shell"><div className="neighborhoodScoreGrid"><div className="bigScore"><span>تقييم أثيلدار</span><b>{n.score}</b><small>/100</small></div><div><TrendingUp/><small>الطلب</small><b>{n.demand}</b></div><div><Footprints/><small>قابلية المشي</small><b>{n.walk}</b></div><div><Home/><small>ملاءمة العائلات</small><b>{n.family}</b></div></div><div className="neighborhoodContent"><div><h2>قراءة المنطقة</h2><p className="leadText">{n.summary} هذه المؤشرات ضمن نموذج العرض وليست بيانات سوقية رسمية أو توصية استثمارية.</p><h3>نطاق سعري استرشادي</h3><div className="priceBand"><BarChart3/><span><b>{n.price}</b><small>نطاق تجريبي حسب نوع الأصل والموقع داخل الحي</small></span></div></div><div className="districtMap"><span>{n.name}</span><i className="ring rA"/><i className="ring rB"/><i className="ring rC"/></div></div></section><section className="shell neighborhoodRadiusWrap"><NeighborhoodDailyRadius slug={n.slug}/></section><section className="section darkSection neighborhoodExperienceSection"><div className="shell"><NeighborhoodExperience neighborhood={n}/></div></section>{ps.length>0&&<section className="section softSection"><div className="shell"><div className="sectionHead"><div><p className="eyebrow">عقارات مرتبطة</p><h2>فرص في {n.city}</h2></div><Link href="/properties" className="textLink">كل العقارات <ArrowLeft/></Link></div><div className="propertyGrid">{ps.map(p=><PropertyCard p={p} key={p.slug}/>)}</div></div></section>}</>}
