import Link from 'next/link';
import { ArrowLeft, BadgeCheck, Building2, ChartNoAxesCombined, Home, MapPinned, Search, ShieldCheck, Sparkles, WalletCards } from 'lucide-react';
import { properties, projects, neighborhoods, money } from '@/lib/atheeldar-data';
import { PropertyCard } from '@/components/atheeldar/PropertyCard';

export default function HomePage(){
  return <>
    <section className="homeHero"><div className="heroPhoto"/><div className="heroShade"/><div className="shell heroInner"><p className="eyebrow light">منصة عقارية سعودية بمعايير استثنائية</p><h1>العقار المناسب.<br/><em>بقرار أذكى.</em></h1><p>أثيلدار تجمع البحث، المقارنة، الأحياء، المشاريع، الاستثمار والتمويل في تجربة واحدة منظمة — لكن عبر صفحات متخصصة فعلًا، لا صفحة طويلة واحدة.</p><form action="/properties" method="get" className="homeSearch"><Search/><input name="q" placeholder="جرّب: فيلا بالرياض أقل من 7 مليون و5 غرف"/><button>ابحث بذكاء</button></form><div className="heroProof"><span><ShieldCheck/> بيانات عرض موثقة تجريبيًا</span><span><Sparkles/> بحث باللغة الطبيعية</span><span><BadgeCheck/> رحلة عميل متكاملة</span></div></div></section>
    <section className="featureNav shell"><Link href="/properties"><Home/><span><b>العقارات</b><small>بحث، تصفية، خريطة ومقارنة</small></span><ArrowLeft/></Link><Link href="/projects"><Building2/><span><b>المشاريع</b><small>مشاريع جديدة وخطط تسليم</small></span><ArrowLeft/></Link><Link href="/neighborhoods"><MapPinned/><span><b>دليل الأحياء</b><small>مؤشرات وقراءة للموقع</small></span><ArrowLeft/></Link><Link href="/investment"><ChartNoAxesCombined/><span><b>الاستثمار</b><small>عائد ونمو وسيناريوهات</small></span><ArrowLeft/></Link><Link href="/finance"><WalletCards/><span><b>التمويل</b><small>محاكاة وقدرة شرائية</small></span><ArrowLeft/></Link></section>
    <section className="section shell"><div className="sectionHead"><div><p className="eyebrow">مختارات أثيلدار</p><h2>عقارات تستحق <em>التوقف عندها</em></h2></div><Link href="/properties" className="textLink">عرض كل العقارات <ArrowLeft/></Link></div><div className="propertyGrid">{properties.filter(p=>p.featured).slice(0,3).map(p=><PropertyCard key={p.slug} p={p}/>)}</div></section>
    <section className="darkSection"><div className="shell projectFeature"><div><p className="eyebrow light">مشروع مختار</p><h2>{projects[0].name}</h2><p>{projects[0].description}</p><div className="projectStats"><div><small>يبدأ من</small><b>{money(projects[0].from)} ر.س</b></div><div><small>عدد الوحدات</small><b>{projects[0].units}</b></div><div><small>التسليم</small><b>{projects[0].delivery}</b></div></div><Link href={`/projects/${projects[0].slug}`} className="lightCta">استكشف المشروع <ArrowLeft/></Link></div><img src={projects[0].image} alt={projects[0].name}/></div></section>
    <section className="section shell"><div className="sectionHead"><div><p className="eyebrow">قرار الموقع</p><h2>الأحياء ليست <em>مجرد أسماء</em></h2></div><Link href="/neighborhoods" className="textLink">فتح دليل الأحياء <ArrowLeft/></Link></div><div className="neighborhoodStrip">{neighborhoods.slice(0,4).map(n=><Link href={`/neighborhoods/${n.slug}`} key={n.slug}><img src={n.image}/><div><span>{n.city}</span><b>{n.name}</b><small>تقييم أثيلدار {n.score}/100</small></div></Link>)}</div></section>
    <section className="splitCta"><div className="shell splitCtaInner"><div><p className="eyebrow light">للمشتري والمستثمر</p><h2>حاسبة التمويل ومختبر الاستثمار ليسا إضافات جانبية.</h2><p>هما مساران مستقلان يساعدان العميل على فهم الصفقة قبل التواصل.</p></div><div className="ctaCards"><Link href="/investment"><ChartNoAxesCombined/><b>مختبر المستثمر</b><span>العائد، صافي الدخل، القيمة المستقبلية</span></Link><Link href="/finance"><WalletCards/><b>مختبر التمويل</b><span>القسط، مبلغ التمويل، نسبة العبء</span></Link></div></div></section>
  </>
}
