import Link from 'next/link';
import { ArrowLeft, BadgeCheck, Building2, ChartNoAxesCombined, Home, MapPinned, Search, ShieldCheck, Sparkles, TrendingUp, WalletCards, Zap, Target, Layers3, Compass, BellRing, BookOpenText, Route } from 'lucide-react';
import { properties, projects, neighborhoods, money } from '@/lib/atheeldar-data';
import { PropertyCard } from '@/components/atheeldar/PropertyCard';
import { HomeJourneyPlanner } from '@/components/atheeldar/ExperienceTools';
import { HomeImmersion } from '@/components/atheeldar/HomeImmersion';

export default function HomePage(){
  const avgScore=Math.round(properties.reduce((s,p)=>s+p.score,0)/properties.length);
  return <>
    <section className="homeHero"><div className="heroPhoto"/><div className="heroShade"/><div className="shell heroInner"><div className="heroKicker"><span><Zap size={14}/> تجربة عقارية متعددة المسارات</span><span>SAUDI REAL ESTATE EXPERIENCE</span></div><h1><span className="heroLine">العقار المناسب.</span><span className="heroAccent">بقرار أذكى.</span></h1><p>أثيلدار تجمع البحث، المقارنة، الأحياء، المشاريع، الاستثمار والتمويل في منظومة واحدة تساعد العميل على الانتقال من الاكتشاف إلى القرار بثقة أكبر.</p><form action="/properties" method="get" className="homeSearch"><Search/><input name="q" placeholder="جرّب: فيلا بالرياض أقل من 7 مليون و5 غرف"/><button>ابحث بذكاء</button></form><div className="heroProof"><span><ShieldCheck/> بيانات عرض واضحة</span><span><Sparkles/> بحث باللغة الطبيعية</span><span><BadgeCheck/> رحلة عميل مترابطة</span></div><div className="heroMetrics"><div><b>{properties.length}</b><span>عقار نموذجي غني بالبيانات</span></div><div><b>{projects.length}</b><span>مشاريع بصفحات مستقلة</span></div><div><b>{neighborhoods.length}</b><span>ملفات أحياء قابلة للمقارنة</span></div><div><b>{avgScore}</b><span>متوسط تقييم النموذج</span></div></div></div></section>
    <section className="featureNav shell"><Link href="/properties"><Home/><span><b>العقارات</b><small>بحث، تصفية، خريطة ومقارنة</small></span><ArrowLeft/></Link><Link href="/projects"><Building2/><span><b>المشاريع</b><small>مشاريع جديدة وخطط دفع</small></span><ArrowLeft/></Link><Link href="/neighborhoods"><MapPinned/><span><b>دليل الأحياء</b><small>مؤشرات ومقارنة مباشرة</small></span><ArrowLeft/></Link><Link href="/investment"><ChartNoAxesCombined/><span><b>الاستثمار</b><small>سيناريوهات وعوائد ومخاطر</small></span><ArrowLeft/></Link><Link href="/finance"><WalletCards/><span><b>التمويل</b><small>قدرة شرائية وتكلفة كلية</small></span><ArrowLeft/></Link></section>
    <section className="marketPulse"><div className="shell marketPulseInner"><div><p className="eyebrow light">ATHEELDAR MARKET PULSE</p><h2>اقرأ المشهد قبل أن تفتح الإعلان.</h2><p>مؤشرات نموذجية تساعد على شرح كيف يمكن للمنصة أن تحوّل البيانات إلى سياق مفهوم للمستخدم.</p></div><div className="pulseCards"><Link href="/neighborhoods/hittin"><TrendingUp/><span>طلب فاخر</span><b>حطين · 94/100</b><small>ملف حي غني بالسياق</small></Link><Link href="/projects"><Layers3/><span>مشاريع جديدة</span><b>{projects[0].progress}% تقدم</b><small>{projects[0].name}</small></Link><Link href="/investment"><Target/><span>فرص استثمار</span><b>{properties.filter(p=>p.investment).length} أصول</b><small>اختبر العائد والسيناريو</small></Link></div></div></section>
    <section className="section shell"><HomeJourneyPlanner/></section>
    <section className="shell experienceGateway"><Link href="/market-studio"><span>01 · MARKET STUDIO</span><h2>اكتشف السوق قبل أن تبحث عن الإعلان.</h2><p>مدن، شرائح، Watchlist ومصفوفة فرص في تجربة تحريرية واحدة.</p><strong>افتح استوديو السوق <ArrowLeft/></strong></Link><Link href="/decision-center"><span>02 · DECISION CENTER</span><h2>حوّل الاهتمام إلى مسار قرار.</h2><p>هدف + مدينة + ميزانية = عقار وحي وتمويل ومستشار داخل شاشة واحدة.</p><strong>ابدأ مركز القرار <ArrowLeft/></strong></Link></section>
    <section className="shell phase6Discovery"><div className="phase6DiscoveryHead"><p className="eyebrow">DISCOVER DIFFERENTLY</p><h2>أربع طرق جديدة <em>للوصول إلى القرار</em></h2><p>البحث ليس نقطة البداية الوحيدة. أثيلدار تسمح لك أن تبدأ من أسلوب الحياة، المجموعة، المعرفة أو يوم المعاينات.</p></div><div className="phase6DiscoveryGrid"><Link href="/lifestyle"><Compass/><span>01</span><b>مكتشف أسلوب الحياة</b><small>ابدأ من الهدوء، العائلة، البحر أو الإيقاع الحضري.</small><ArrowLeft/></Link><Link href="/collections"><Layers3/><span>02</span><b>مجموعات أثيلدار</b><small>مسارات تحريرية تجمع أصولًا تحت فكرة واضحة.</small><ArrowLeft/></Link><Link href="/briefs"><BookOpenText/><span>03</span><b>موجز أثيلدار</b><small>اقرأ قبل أن تقارن، وادخل القرار بأسئلة أفضل.</small><ArrowLeft/></Link><Link href="/viewing-planner"><Route/><span>04</span><b>مخطط المعاينات</b><small>حوّل المفضلة إلى يوم زيارات منظم وقابل للمراجعة.</small><ArrowLeft/></Link></div></section>
    <HomeImmersion/>
    <section className="section shell"><div className="sectionHead"><div><p className="eyebrow">مختارات أثيلدار</p><h2>عقارات تستحق <em>التوقف عندها</em></h2></div><Link href="/properties" className="textLink">عرض كل العقارات <ArrowLeft/></Link></div><div className="propertyGrid">{properties.filter(p=>p.featured).slice(0,3).map(p=><PropertyCard key={p.slug} p={p}/>)}</div></section>
    <section className="darkSection"><div className="shell projectFeature"><div><p className="eyebrow light">مشروع مختار</p><h2>{projects[0].name}</h2><p>{projects[0].description}</p><div className="projectStats"><div><small>يبدأ من</small><b>{money(projects[0].from)} ر.س</b></div><div><small>عدد الوحدات</small><b>{projects[0].units}</b></div><div><small>التسليم</small><b>{projects[0].delivery}</b></div></div><Link href={`/projects/${projects[0].slug}`} className="lightCta">استكشف المشروع <ArrowLeft/></Link></div><div className="projectVisualFrame"><img src={projects[0].image} alt={projects[0].name}/><span>PROJECT 01 · {projects[0].city}</span></div></div></section>
    <section className="section shell"><div className="sectionHead"><div><p className="eyebrow">قرار الموقع</p><h2>الأحياء ليست <em>مجرد أسماء</em></h2></div><Link href="/neighborhoods" className="textLink">فتح دليل الأحياء <ArrowLeft/></Link></div><div className="neighborhoodStrip">{neighborhoods.slice(0,4).map(n=><Link href={`/neighborhoods/${n.slug}`} key={n.slug}><img src={n.image} alt={n.name}/><div><span>{n.city}</span><b>{n.name}</b><small>تقييم أثيلدار {n.score}/100</small></div></Link>)}</div></section>
    <section className="splitCta"><div className="shell splitCtaInner"><div><p className="eyebrow light">للمشتري والمستثمر</p><h2>الأرقام جزء من تجربة القرار، وليست صفحة جانبية.</h2><p>اختبر تمويلك، العائد، السيناريوهات ثم ارجع إلى العقار والسياق المكاني بنفس الرحلة.</p></div><div className="ctaCards"><Link href="/investment"><ChartNoAxesCombined/><b>مختبر المستثمر</b><span>سيناريوهات، عائد، صافي دخل وقيمة مستقبلية</span></Link><Link href="/finance"><WalletCards/><b>مختبر التمويل</b><span>القسط، التكلفة الكلية، العبء والقدرة الشرائية</span></Link></div></div></section>
  </>
}
