'use client';
import { useEffect, useMemo, useState } from 'react';
import { properties, money, type Property } from '@/lib/atheeldar-data';
import { CalendarDays, CheckCircle2, Heart, Phone, Save, TrendingUp, WalletCards, ArrowLeftRight, UserRoundCheck } from 'lucide-react';

function safe(key:string){if(typeof window==='undefined')return [];try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return []}}

export function PropertyActionPanel({property}:{property:Property}){
  const [fav,setFav]=useState(false); const [done,setDone]=useState(false);
  useEffect(()=>setFav(safe('atheeldar-favorites').includes(property.slug)),[property.slug]);
  const toggle=()=>{const s=new Set<string>(safe('atheeldar-favorites'));fav?s.delete(property.slug):s.add(property.slug);localStorage.setItem('atheeldar-favorites',JSON.stringify([...s]));setFav(!fav);window.dispatchEvent(new Event('atheeldar:favorites'))};
  const book=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const bookings=safe('atheeldar-bookings');bookings.unshift({id:Date.now(),property:property.title,slug:property.slug,date:fd.get('date'),time:fd.get('time'),name:fd.get('name'),phone:fd.get('phone'),status:'requested'});localStorage.setItem('atheeldar-bookings',JSON.stringify(bookings.slice(0,20)));setDone(true)};
  return <aside className="actionPanel"><div className="actionPrice"><span>{property.purpose}</span><b>{money(property.price)} ر.س</b>{property.purpose==='للإيجار'&&<small>سنويًا</small>}</div><button className={`favoriteWide ${fav?'on':''}`} onClick={toggle}><Heart size={18} fill={fav?'currentColor':'none'}/>{fav?'محفوظ في المفضلة':'حفظ في المفضلة'}</button><div className="panelDivider"/><h3>احجز معاينة خاصة</h3>{done?<div className="successBox"><CheckCircle2/><b>تم تسجيل طلب المعاينة</b><p>سيظهر الآن داخل مساحة العميل وبوابة المستشار التجريبية.</p></div>:<form onSubmit={book} className="bookingForm"><label>الاسم<input name="name" required placeholder="الاسم الكامل"/></label><label>الجوال<input name="phone" required placeholder="05xxxxxxxx" inputMode="tel"/></label><div className="form2"><label>اليوم<input name="date" type="date" required/></label><label>الوقت<select name="time"><option>10:00 ص</option><option>1:00 م</option><option>4:00 م</option><option>7:00 م</option></select></label></div><button className="primaryWide"><CalendarDays size={17}/> تأكيد موعد المعاينة</button></form>}<a className="callLink" href="tel:+966115550900"><Phone size={17}/> تواصل هاتفيًا</a></aside>
}

export function InvestmentLab(){
  const [price,setPrice]=useState(2500000),[rent,setRent]=useState(180000),[occupancy,setOccupancy]=useState(92),[costs,setCosts]=useState(26000),[growth,setGrowth]=useState(4.5);
  const gross=rent/price*100, net=((rent*occupancy/100)-costs)/price*100, future=price*Math.pow(1+growth/100,5), income=rent*occupancy/100-costs;
  return <div className="toolGrid"><section className="calculatorBox"><div className="toolHeader"><TrendingUp/><div><span>ATHEELDAR INVESTMENT LAB</span><h2>مختبر المستثمر</h2></div></div><p>غيّر الفرضيات وشاهد أثرها مباشرة. جميع النتائج تقديرية لأغراض العرض وليست توصية استثمارية.</p><label>قيمة العقار <b>{money(price)} ر.س</b><input type="range" min="500000" max="10000000" step="100000" value={price} onChange={e=>setPrice(+e.target.value)}/></label><label>الدخل الإيجاري السنوي<input type="number" value={rent} onChange={e=>setRent(+e.target.value)}/></label><div className="form2"><label>الإشغال المتوقع %<input type="number" min="0" max="100" value={occupancy} onChange={e=>setOccupancy(+e.target.value)}/></label><label>المصاريف السنوية<input type="number" value={costs} onChange={e=>setCosts(+e.target.value)}/></label></div><label>نمو القيمة السنوي %<input type="number" step="0.1" value={growth} onChange={e=>setGrowth(+e.target.value)}/></label></section><section className="metricBoard"><div><span>العائد الإجمالي</span><b>{gross.toFixed(2)}%</b><small>قبل المصاريف والإشغال</small></div><div><span>العائد الصافي التقديري</span><b>{net.toFixed(2)}%</b><small>بعد المصاريف والإشغال</small></div><div><span>صافي الدخل السنوي</span><b>{money(Math.round(income))}</b><small>ر.س / سنوي</small></div><div className="metricFeatured"><span>القيمة بعد 5 سنوات</span><b>{money(Math.round(future))} ر.س</b><small>على فرض نمو سنوي {growth}%</small></div></section></div>
}

export function FinanceLab(){
  const [price,setPrice]=useState(2000000),[down,setDown]=useState(20),[years,setYears]=useState(20),[rate,setRate]=useState(4.75),[income,setIncome]=useState(28000),[debt,setDebt]=useState(2500);
  const loan=price*(1-down/100), r=rate/100/12,n=years*12,pmt=r?loan*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):loan/n,burden=(pmt+debt)/income*100,afford=burden<45?'مرونة جيدة':burden<55?'يحتاج موازنة':'ضغط تمويلي مرتفع';
  return <div className="financeWorkspace"><section className="calculatorBox"><div className="toolHeader"><WalletCards/><div><span>SMART FINANCE</span><h2>محاكاة التمويل</h2></div></div><label>سعر العقار <b>{money(price)} ر.س</b><input type="range" min="500000" max="8000000" step="50000" value={price} onChange={e=>setPrice(+e.target.value)}/></label><div className="form2"><label>الدفعة الأولى %<input type="number" value={down} onChange={e=>setDown(+e.target.value)}/></label><label>مدة التمويل<select value={years} onChange={e=>setYears(+e.target.value)}><option value="10">10 سنوات</option><option value="15">15 سنة</option><option value="20">20 سنة</option><option value="25">25 سنة</option><option value="30">30 سنة</option></select></label></div><label>معدل سنوي افتراضي %<input type="number" step="0.05" value={rate} onChange={e=>setRate(+e.target.value)}/></label><div className="form2"><label>الدخل الشهري<input type="number" value={income} onChange={e=>setIncome(+e.target.value)}/></label><label>التزامات شهرية<input type="number" value={debt} onChange={e=>setDebt(+e.target.value)}/></label></div></section><section className="financeSummary"><span>القسط الشهري التقديري</span><b>{money(Math.round(pmt))} ر.س</b><div className="financeFacts"><div><small>مبلغ التمويل</small><strong>{money(Math.round(loan))} ر.س</strong></div><div><small>نسبة العبء التقديرية</small><strong>{burden.toFixed(1)}%</strong></div><div><small>قراءة أولية</small><strong>{afford}</strong></div></div><p>هذه أداة توضيحية ولا تمثل عرضًا تمويليًا أو موافقة ائتمانية.</p></section></div>
}

export function AdvisorBooking({advisor}:{advisor:string}){const [done,setDone]=useState(false);return <form className="advisorBook" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const arr=safe('atheeldar-bookings');arr.unshift({id:Date.now(),advisor,name:fd.get('name'),phone:fd.get('phone'),date:fd.get('date'),status:'advisor'});localStorage.setItem('atheeldar-bookings',JSON.stringify(arr));setDone(true)}}>{done?<div className="successBox"><UserRoundCheck/><b>تم حجز جلسة مع {advisor}</b></div>:<><input name="name" required placeholder="الاسم"/><input name="phone" required placeholder="رقم الجوال"/><input name="date" type="date" required/><button>احجز جلسة</button></>}</form>}

export function ClientSpace(){
  const [tick,setTick]=useState(0); useEffect(()=>{const h=()=>setTick(v=>v+1);window.addEventListener('storage',h);return()=>window.removeEventListener('storage',h)},[]);
  const favSlugs=safe('atheeldar-favorites') as string[], favs=properties.filter(p=>favSlugs.includes(p.slug)), searches=safe('atheeldar-saved-searches'), bookings=safe('atheeldar-bookings');
  return <div className="clientGrid"><section className="clientMain"><div className="clientIntro"><span>ATHEELDAR CLIENT SPACE</span><h2>مساحتك العقارية في مكان واحد</h2><p>نموذج لحساب مستخدم يجمع المفضلة والبحث المحفوظ ومواعيد المعاينات.</p></div><h3 id="favorites">العقارات المحفوظة</h3>{favs.length?<div className="savedList">{favs.map(p=><a href={`/properties/${p.slug}`} key={p.slug}><img src={p.image}/><span><b>{p.title}</b><small>{p.city} · {money(p.price)} ر.س</small></span></a>)}</div>:<div className="emptyBox">لا توجد عقارات محفوظة بعد.</div>}<h3>عمليات البحث المحفوظة</h3>{searches.length?<div className="simpleList">{searches.map((s:any)=><div key={s.id}><Save size={17}/><span>{s.query||`${s.city} · ${s.type}`}</span><small>حتى {money(s.max||0)} ر.س</small></div>)}</div>:<div className="emptyBox">احفظ بحثًا من صفحة العقارات ليظهر هنا.</div>}</section><aside className="clientAside"><h3>المواعيد</h3>{bookings.length?<div className="bookingList">{bookings.map((b:any)=><div key={b.id}><CalendarDays/><span><b>{b.property||b.advisor||'جلسة عقارية'}</b><small>{b.date} {b.time||''}</small></span></div>)}</div>:<p>لا توجد مواعيد بعد.</p>}<a href="/properties" className="primaryWide">استكشف العقارات</a></aside></div>
}

const seeded=[{id:'L-1024',name:'عبدالله القحطاني',goal:'فيلا شمال الرياض',status:'new',value:6800000},{id:'L-1021',name:'نورة السبيعي',goal:'استثمار شقة جدة',status:'contacted',value:2200000},{id:'L-1018',name:'محمد الزهراني',goal:'أرض تطوير',status:'viewing',value:3100000},{id:'L-1014',name:'هند المطيري',goal:'بنتهاوس الرياض',status:'negotiation',value:4500000}];
export function CRMBoard(){const [refresh,setRefresh]=useState(0);const stored=safe('atheeldar-leads');const all=[...stored,...seeded];const statuses=[['new','جديد'],['contacted','تم التواصل'],['viewing','معاينة'],['negotiation','تفاوض']];const next=(id:string)=>{const arr=safe('atheeldar-leads');const x=arr.find((a:any)=>String(a.id)===String(id));if(x){x.status=x.status==='new'?'contacted':x.status==='contacted'?'viewing':'negotiation';localStorage.setItem('atheeldar-leads',JSON.stringify(arr));setRefresh(v=>v+1)}};return <><div className="crmKpis"><div><span>Leads النشطة</span><b>{all.length}</b></div><div><span>قيمة الفرص النموذجية</span><b>{money(all.reduce((a:number,b:any)=>a+(b.value||0),0))}</b></div><div><span>في مرحلة المعاينة</span><b>{all.filter((x:any)=>x.status==='viewing').length}</b></div><div><span>تفاوض</span><b>{all.filter((x:any)=>x.status==='negotiation').length}</b></div></div><div className="crmBoard">{statuses.map(([key,label])=><section key={key}><h3>{label}<span>{all.filter((x:any)=>x.status===key).length}</span></h3>{all.filter((x:any)=>x.status===key).map((l:any)=><article key={l.id}><small>{l.id}</small><b>{l.name}</b><p>{l.goal}</p>{l.value&&<span>{money(l.value)} ر.س</span>}{String(l.id).startsWith('L-')?null:<button onClick={()=>next(String(l.id))}>نقل للمرحلة التالية</button>}</article>)}</section>)}</div></>}

export function ContactLeadForm(){const [done,setDone]=useState(false);return <form className="contactLeadForm" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const arr=safe('atheeldar-leads');arr.unshift({id:'WEB-'+Date.now(),name:fd.get('name'),phone:fd.get('phone'),goal:fd.get('goal'),details:fd.get('details'),status:'new',created:new Date().toISOString()});localStorage.setItem('atheeldar-leads',JSON.stringify(arr));setDone(true)}}>{done?<div className="successBox"><CheckCircle2/><b>وصل طلبك إلى بوابة المستشار التجريبية</b><p>يمكن مشاهدة الـLead الجديد داخل صفحة لوحة التشغيل.</p></div>:<><div className="form2"><label>الاسم<input name="name" required/></label><label>الجوال<input name="phone" required/></label></div><label>الهدف<select name="goal"><option>شراء عقار</option><option>استئجار عقار</option><option>استثمار عقاري</option><option>تسويق عقار</option><option>تمويل</option></select></label><label>تفاصيل الطلب<textarea name="details" rows={5}/></label><button className="primaryWide">إرسال الطلب</button></>}</form>}
