'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowLeft, BadgeCheck, Building2, Check, CheckCircle2, CircleDashed, FileCheck2, Gauge, Heart, Home, MapPinned, Scale, ShieldCheck, Sparkles, Target, UsersRound, WalletCards } from 'lucide-react';
import { neighborhoods, properties, money, type Property } from '@/lib/atheeldar-data';

function read<T=string>(key:string):T[]{if(typeof window==='undefined')return[];try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}}
type BoardMode='سكن'|'عائلة'|'استثمار';
export function DecisionBoard(){
  const [ready,setReady]=useState(false),[mode,setMode]=useState<BoardMode>('سكن'),[budget,setBudget]=useState(4500000);
  const [weights,setWeights]=useState({quality:30,lifestyle:30,investment:15,budget:25});
  const [pool,setPool]=useState<Property[]>([]),[saved,setSaved]=useState(false);
  useEffect(()=>{const id=window.setTimeout(()=>{const ids=[...new Set([...read<string>('atheeldar-favorites'),...read<string>('atheeldar-market-watch')])];const fromSaved=ids.map(s=>properties.find(p=>p.slug===s)).filter(Boolean) as Property[];setPool(fromSaved.length?fromSaved.slice(0,5):properties.filter(p=>p.featured).slice(0,4));setReady(true)},0);return()=>window.clearTimeout(id)},[]);
  const preset=(m:BoardMode)=>{setMode(m);if(m==='سكن')setWeights({quality:35,lifestyle:35,investment:10,budget:20});if(m==='عائلة')setWeights({quality:25,lifestyle:45,investment:5,budget:25});if(m==='استثمار')setWeights({quality:20,lifestyle:10,investment:45,budget:25})};
  const metric=(p:Property)=>{const quality=p.score,lifestyle=Math.min(98,(p.beds>=4?92:82)+(p.newBuild?4:0)),investment=p.investment?Math.min(98,88+(p.yield||0)):Math.max(68,p.score-13),budgetFit=Math.max(45,100-Math.abs(p.price-budget)/Math.max(budget,1)*72);const total=(quality*weights.quality+lifestyle*weights.lifestyle+investment*weights.investment+budgetFit*weights.budget)/(weights.quality+weights.lifestyle+weights.investment+weights.budget);return{quality,lifestyle,investment:Math.round(investment),budgetFit:Math.round(budgetFit),total:Math.round(total)}};
  const ranked=[...pool].sort((a,b)=>metric(b).total-metric(a).total);
  const save=()=>{try{localStorage.setItem('atheeldar-board-snapshot',JSON.stringify({mode,budget,weights,properties:ranked.map(p=>p.slug),savedAt:Date.now()}));setSaved(true);window.setTimeout(()=>setSaved(false),1600)}catch{}};
  if(!ready)return <div className="boardLoading">جاري تجهيز لوحة القرار...</div>;
  return <div className="decisionBoardV7"><section className="boardControls"><div><span>ATHEELDAR DECISION BOARD</span><h2>لا تقارن العقارات <em>بنفس المعيار دائمًا.</em></h2><p>غيّر هدفك وأوزان القرار، لترى كيف تتغير الأولوية بين الأصول المحفوظة. الحساب توضيحي داخل نموذج العرض.</p></div><div className="boardMode">{(['سكن','عائلة','استثمار'] as BoardMode[]).map(x=><button className={mode===x?'active':''} key={x} onClick={()=>preset(x)}>{x}</button>)}</div><label className="boardBudget">الميزانية المستهدفة <b>{money(budget)} ر.س</b><input type="range" min="1000000" max="9000000" step="250000" value={budget} onChange={e=>setBudget(+e.target.value)}/></label><div className="weightGrid"><label>جودة الأصل <b>{weights.quality}%</b><input type="range" min="5" max="60" value={weights.quality} onChange={e=>setWeights({...weights,quality:+e.target.value})}/></label><label>نمط الحياة <b>{weights.lifestyle}%</b><input type="range" min="5" max="60" value={weights.lifestyle} onChange={e=>setWeights({...weights,lifestyle:+e.target.value})}/></label><label>الاستثمار <b>{weights.investment}%</b><input type="range" min="5" max="60" value={weights.investment} onChange={e=>setWeights({...weights,investment:+e.target.value})}/></label><label>الميزانية <b>{weights.budget}%</b><input type="range" min="5" max="60" value={weights.budget} onChange={e=>setWeights({...weights,budget:+e.target.value})}/></label></div><button className="boardSave" onClick={save}><CheckCircle2/>{saved?'تم حفظ اللقطة':'احفظ لقطة القرار'}</button></section><section className="boardRanking"><div className="boardRankingHead"><span>الترتيب الحالي</span><small>{pool.some(p=>read<string>('atheeldar-favorites').includes(p.slug))?'يعتمد على محفوظاتك الحالية':'يستخدم أصولًا توضيحية حتى تحفظ عقاراتك'}</small></div>{ranked.map((p,i)=>{const m=metric(p);return <article key={p.slug} className={i===0?'winner':''}><div className="boardRank"><span>0{i+1}</span><b>{m.total}</b><small>/100</small></div><img src={p.image} alt={p.title}/><div className="boardAsset"><small>{p.city} · {p.district}</small><h3>{p.title}</h3><b>{money(p.price)} ر.س</b><div className="boardMicro"><span>الجودة {m.quality}</span><span>الحياة {m.lifestyle}</span><span>الاستثمار {m.investment}</span><span>الميزانية {m.budgetFit}</span></div></div><Link href={`/properties/${p.slug}`}>فتح <ArrowLeft/></Link></article>})}</section></div>
}

type Priority='العائلة'|'الحركة'|'الهدوء'|'الاستثمار';
export function DailyFitPlanner({property}:{property:Property}){
  const n=neighborhoods.find(x=>x.slug===property.neighborhoodSlug)||neighborhoods[0];
  const [priorities,setPriorities]=useState<Priority[]>(['العائلة','الحركة']);
  const toggle=(x:Priority)=>setPriorities(v=>v.includes(x)?v.filter(y=>y!==x):v.length<3?[...v,x]:[v[1],v[2],x]);
  const base={family:n.family==='ممتاز'?95:n.family==='جيد'?82:72,mobility:n.walk==='ممتاز'?94:n.walk==='جيد'?84:72,quiet:property.type==='فيلا'?92:property.city==='الرياض'?80:83,investment:property.investment?94:Math.max(70,property.score-10)};
  const map:Record<Priority,number>={'العائلة':base.family,'الحركة':base.mobility,'الهدوء':base.quiet,'الاستثمار':base.investment};
  const fit=priorities.length?Math.round(priorities.reduce((s,x)=>s+map[x],0)/priorities.length):property.score;
  return <section className="dailyFitPlanner"><div className="dailyFitIntro"><span>DAILY FIT PLANNER</span><h2>هل يناسب العقار <em>يومك الحقيقي؟</em></h2><p>اختر حتى ثلاث أولويات. النتيجة نموذجية وتعتمد على خصائص الحي والعقار داخل بيانات العرض، وليست وقت تنقل حيًا.</p><div className="priorityChips">{(['العائلة','الحركة','الهدوء','الاستثمار'] as Priority[]).map(x=><button key={x} className={priorities.includes(x)?'active':''} onClick={()=>toggle(x)}>{priorities.includes(x)?<Check/>:<CircleDashed/>}{x}</button>)}</div></div><div className="dailyFitScore"><span><Sparkles/> ملاءمة يومية نموذجية</span><b>{fit}</b><small>/100</small><i><em style={{width:`${fit}%`}}/></i></div><div className="dailyFitMetrics"><article><UsersRound/><span><small>العائلة</small><b>{base.family}</b></span></article><article><MapPinned/><span><small>الحركة اليومية</small><b>{base.mobility}</b></span></article><article><Home/><span><small>الهدوء</small><b>{base.quiet}</b></span></article><article><Target/><span><small>الاستثمار</small><b>{base.investment}</b></span></article></div><Link href={`/neighborhoods/${n.slug}`}>افتح ملف {n.name} <ArrowLeft/></Link></section>
}

type TrustTab='الإعلان'|'العقار'|'الصفقة';
export function TrustCenter(){
  const [tab,setTab]=useState<TrustTab>('الإعلان');
  const content={
    'الإعلان':{title:'وضوح الإعلان',copy:'ما الذي يجب أن يكون ظاهرًا قبل أن تطلب المعاينة؟',items:['السعر والغرض والمساحة','الموقع والحي بوضوح','المواصفات الجوهرية','تمييز البيانات النموذجية من الرسمية']},
    'العقار':{title:'فحص الأصل',copy:'طبقة التحقق التي تتحول من عرض رقمي إلى قرار واقعي.',items:['حالة العقار الفعلية','المخططات والرخص','الضمانات والصيانة','المطابقة بين الصور والواقع']},
    'الصفقة':{title:'جاهزية الصفقة',copy:'ما يجب مراجعته قبل أي التزام مالي أو قانوني.',items:['الملكية والصك','الرسوم والالتزامات','شروط التمويل','العقود ومراحل الإفراغ']},
  }[tab];
  return <div className="trustCenterV7"><section className="trustManifesto"><ShieldCheck/><span>ATHEELDAR TRUST FRAMEWORK</span><h2>الثقة ليست شارة. <em>هي سلسلة تحقق.</em></h2><p>في هذا النموذج، كلمة “موثق تجريبيًا” تعني اكتمال بيانات العرض داخل التجربة فقط. أي استخدام فعلي يحتاج تحققًا رسميًا من المستندات والجهات المختصة.</p><div className="trustTabs">{(['الإعلان','العقار','الصفقة'] as TrustTab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div></section><section className="trustDetail"><span>0{(['الإعلان','العقار','الصفقة'] as TrustTab[]).indexOf(tab)+1}</span><h3>{content.title}</h3><p>{content.copy}</p><div>{content.items.map(x=><b key={x}><CheckCircle2/>{x}</b>)}</div></section><section className="trustLevels"><article><BadgeCheck/><span><small>LEVEL 01</small><b>بيانات عرض مكتملة</b><p>المحتوى والمواصفات الأساسية متاحة للمقارنة.</p></span></article><article><FileCheck2/><span><small>LEVEL 02</small><b>مستندات قيد المراجعة</b><p>طبقة تشغيلية تتطلب رفع والتحقق من المستندات.</p></span></article><article><Scale/><span><small>LEVEL 03</small><b>جاهزية تعاقد</b><p>مرحلة قانونية ومالية لا يمثلها نموذج Portfolio الحالي.</p></span></article></section><section className="trustCta"><div><small>TRUST BEFORE TRANSACTION</small><b>اجعل الشفافية جزءًا من المنتج نفسه.</b></div><Link href="/properties">استكشف العقارات <ArrowLeft/></Link></section></div>
}
