'use client';
import { useEffect, useMemo, useState } from 'react';
import { properties, type Property, money } from '@/lib/atheeldar-data';
import { PropertyCard } from './PropertyCard';
import { Search, SlidersHorizontal, Map, List, X, Sparkles, BellRing, Scale, ArrowDownUp, BadgeCheck, TrendingUp, Gem, Building2 } from 'lucide-react';

type Quick='الكل'|'فاخر'|'موثق'|'جديد'|'استثماري';
type Sort='match'|'priceLow'|'priceHigh'|'score'|'area';

export function PropertyExplorer({initialQuery=''}:{initialQuery?:string}){
  const [query,setQuery]=useState(initialQuery); const [city,setCity]=useState('الكل'); const [type,setType]=useState('الكل'); const [purpose,setPurpose]=useState('الكل'); const [max,setMax]=useState(10000000); const [beds,setBeds]=useState(0); const [view,setView]=useState<'list'|'map'>('list'); const [compare,setCompare]=useState<string[]>([]); const [smartNote,setSmartNote]=useState(''); const [quick,setQuick]=useState<Quick>('الكل'); const [sort,setSort]=useState<Sort>('match');
  useEffect(()=>{if(initialQuery)applySmart(initialQuery)},[]);
  function applySmart(q:string){const t=q.trim(); if(!t)return; setQuery(t); if(/الرياض/.test(t))setCity('الرياض');else if(/جدة/.test(t))setCity('جدة');else if(/الخبر/.test(t))setCity('الخبر');else if(/الدرعية/.test(t))setCity('الدرعية'); if(/فيلا/.test(t))setType('فيلا');else if(/شقة/.test(t))setType('شقة');else if(/بنتهاوس/.test(t))setType('بنتهاوس');else if(/أرض/.test(t))setType('أرض');else if(/مكتب/.test(t))setType('مكتب');else if(/تاون/.test(t))setType('تاون هاوس'); const m=t.match(/(?:أقل من|تحت|حتى)\s*(\d+(?:\.\d+)?)\s*(مليون|م)/); if(m)setMax(Math.round(parseFloat(m[1])*1000000)); const b=t.match(/(\d+)\s*(?:غرف|غرفة)/); if(b)setBeds(parseInt(b[1])); if(/إيجار|للإيجار/.test(t))setPurpose('للإيجار');else if(/شراء|للبيع|بيع/.test(t))setPurpose('للبيع'); if(/استثمار|عائد/.test(t))setQuick('استثماري');else if(/جديد|حديث/.test(t))setQuick('جديد');else if(/فاخر|فخم/.test(t))setQuick('فاخر');else if(/موثق/.test(t))setQuick('موثق'); setSmartNote('فهمنا الإشارات الرئيسية وحوّلناها إلى فلاتر. يمكنك تعديل أي اختيار يدويًا.');}
  const filtered=useMemo(()=>{const list=properties.filter(p=>(city==='الكل'||p.city===city)&&(type==='الكل'||p.type===type)&&(purpose==='الكل'||p.purpose===purpose)&&p.price<=max&&p.beds>=beds&&(quick==='الكل'||(quick==='فاخر'?p.score>=92:quick==='موثق'?p.verified:quick==='جديد'?!!p.newBuild:!!p.investment)));return [...list].sort((a,b)=>sort==='priceLow'?a.price-b.price:sort==='priceHigh'?b.price-a.price:sort==='score'?b.score-a.score:sort==='area'?b.area-a.area:(b.score+(b.featured?4:0))-(a.score+(a.featured?4:0)))},[city,type,purpose,max,beds,quick,sort]);
  const toggleCompare=(slug:string)=>setCompare(v=>v.includes(slug)?v.filter(x=>x!==slug):(v.length<3?[...v,slug]:v));
  const save=()=>{const s=JSON.parse(localStorage.getItem('atheeldar-saved-searches')||'[]');const fingerprint=JSON.stringify({query,city,type,purpose,max,beds,quick});if(s.some((x:any)=>x.fingerprint===fingerprint)){alert('هذا البحث محفوظ بالفعل.');return}s.unshift({id:Date.now(),query,city,type,purpose,max,beds,quick,fingerprint});localStorage.setItem('atheeldar-saved-searches',JSON.stringify(s.slice(0,10)));alert('تم حفظ البحث داخل مساحة العميل.');};
  const reset=()=>{setCity('الكل');setType('الكل');setPurpose('الكل');setMax(10000000);setBeds(0);setQuery('');setSmartNote('');setQuick('الكل');setSort('match')};
  return <>
    <section className="smartSearchPanel">
      <div className="smartSearchTop"><div><span className="tinyLabel"><Sparkles size={15}/> بحث أثيلدار الذكي</span><h2>اكتب ما تبحث عنه بطريقتك</h2></div><button className="softButton" onClick={save}><BellRing size={17}/> احفظ البحث</button></div>
      <div className="smartInput"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&applySmart(query)} placeholder="مثال: فيلا فاخرة بالرياض أقل من 7 مليون و5 غرف"/><button onClick={()=>applySmart(query)}>حلّل الطلب</button></div>{smartNote&&<p className="smartNote">{smartNote}</p>}
      <div className="quickFilters"><button className={quick==='الكل'?'active':''} onClick={()=>setQuick('الكل')}>الكل</button><button className={quick==='فاخر'?'active':''} onClick={()=>setQuick('فاخر')}><Gem/> فاخر</button><button className={quick==='موثق'?'active':''} onClick={()=>setQuick('موثق')}><BadgeCheck/> موثق</button><button className={quick==='جديد'?'active':''} onClick={()=>setQuick('جديد')}><Building2/> جديد</button><button className={quick==='استثماري'?'active':''} onClick={()=>setQuick('استثماري')}><TrendingUp/> استثماري</button></div>
    </section>
    <div className="explorerLayout">
      <aside className="filterPanel"><div className="filterTitle"><SlidersHorizontal size={18}/><b>تصفية النتائج</b></div>
        <label>المدينة<select value={city} onChange={e=>setCity(e.target.value)}><option>الكل</option><option>الرياض</option><option>جدة</option><option>الخبر</option><option>الدرعية</option></select></label>
        <label>نوع العقار<select value={type} onChange={e=>setType(e.target.value)}><option>الكل</option><option>فيلا</option><option>شقة</option><option>بنتهاوس</option><option>تاون هاوس</option><option>مكتب</option><option>أرض</option></select></label>
        <label>الغرض<select value={purpose} onChange={e=>setPurpose(e.target.value)}><option>الكل</option><option>للبيع</option><option>للإيجار</option></select></label>
        <label>أقل عدد غرف<select value={beds} onChange={e=>setBeds(+e.target.value)}><option value="0">أي عدد</option><option value="2">2+</option><option value="3">3+</option><option value="4">4+</option><option value="5">5+</option></select></label>
        <label>حد السعر <b>{money(max)} ر.س</b><input type="range" min="500000" max="10000000" step="250000" value={max} onChange={e=>setMax(+e.target.value)}/></label>
        <button className="resetButton" onClick={reset}><X size={16}/> إعادة الضبط</button>
      </aside>
      <div className="resultsArea"><div className="resultsToolbar"><div><b>{filtered.length} نتيجة</b><span>بيانات نموذجية للمعاينة</span></div><div className="toolbarRight"><label className="sortControl"><ArrowDownUp/><select value={sort} onChange={e=>setSort(e.target.value as Sort)}><option value="match">الأفضل مطابقة</option><option value="score">أعلى تقييم</option><option value="priceLow">السعر: الأقل أولًا</option><option value="priceHigh">السعر: الأعلى أولًا</option><option value="area">الأكبر مساحة</option></select></label><div className="viewToggle"><button className={view==='list'?'active':''} onClick={()=>setView('list')}><List size={17}/> قائمة</button><button className={view==='map'?'active':''} onClick={()=>setView('map')}><Map size={17}/> خريطة</button></div></div></div>
        {view==='list'?<div className="propertyGrid">{filtered.map(p=><PropertyCard key={p.slug} p={p} onCompare={toggleCompare}/>)}</div>:<MapView items={filtered} onCompare={toggleCompare}/>} {filtered.length===0&&<div className="emptyBox"><h3>لا توجد نتائج بهذه الفلاتر</h3><p>غيّر نطاق السعر أو المدينة أو نوع العقار.</p><button onClick={reset}>عرض كل العقارات</button></div>}
      </div>
    </div>
    {compare.length>0&&<CompareTray slugs={compare} close={()=>setCompare([])} remove={toggleCompare}/>}</>
}

function MapView({items,onCompare}:{items:Property[],onCompare:(s:string)=>void}){return <div className="mapExperience"><div className="mapCanvas"><div className="mapRoad r1"/><div className="mapRoad r2"/><div className="mapWater"/><span className="mapLabel one">شمال الرياض</span><span className="mapLabel two">غرب المدينة</span>{items.map(p=><a href={`/properties/${p.slug}`} className="mapPin" key={p.slug} style={{left:`${p.coordinates.x}%`,top:`${p.coordinates.y}%`}}><b>{money(Math.round(p.price/1000))}K</b><span>{p.title}</span></a>)}</div><div className="mapSide"><b>العقارات على الخريطة</b>{items.slice(0,5).map(p=><div key={p.slug}><img src={p.image} alt={p.title}/><span><strong>{p.title}</strong><small>{p.city} · {money(p.price)} ر.س</small></span><button onClick={()=>onCompare(p.slug)}><Scale size={15}/></button></div>)}</div></div>}

function CompareTray({slugs,close,remove}:{slugs:string[],close:()=>void,remove:(s:string)=>void}){const ps=slugs.map(s=>properties.find(p=>p.slug===s)).filter(Boolean) as Property[];return <div className="compareTray"><div className="compareTrayHead"><div><Scale size={18}/><b>مقارنة العقارات ({ps.length}/3)</b></div><button onClick={close}><X/></button></div><div className="compareMini">{ps.map(p=><div key={p.slug}><img src={p.image} alt={p.title}/><span>{p.title}</span><button onClick={()=>remove(p.slug)}>×</button></div>)}</div>{ps.length>=2&&<div className="compareTable"><div><b>السعر</b>{ps.map(p=><span key={p.slug}>{money(p.price)} ر.س</span>)}</div><div><b>سعر المتر</b>{ps.map(p=><span key={p.slug}>{money(Math.round(p.price/p.area))} ر.س</span>)}</div><div><b>المساحة</b>{ps.map(p=><span key={p.slug}>{p.area} م²</span>)}</div><div><b>التقييم</b>{ps.map(p=><span key={p.slug}>{p.score}/100</span>)}</div>{ps.some(p=>p.yield)&&<div><b>العائد</b>{ps.map(p=><span key={p.slug}>{p.yield?`${p.yield}%`:'—'}</span>)}</div>}</div>}</div>}
